export default {
  success: true,
  data: {
    memes: [
      {
        id: "38764534",
        name: "loading hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "2",
      },
      {
        id: "5676453",
        name: "value hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "3",
      },
      {
        id: "098797",
        name: "Search hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "4",
      },
      {
        id: "676886",
        name: "warning. hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "5",
      },
      {
        id: "1235676",
        name: "setBlog hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "6",
      },
      {
        id: "9876563",
        name: "assigned hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "7",
      },
      {
        id: "345654",
        name: "never hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "8",
      },
      {
        id: "20914456",
        name: "defined hotline",
        url: "https:rthlgfgldf",
        width: "1200",
        height: "1200",
        box_count: "9",
      },
    ],
  },
};
